<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <UserSecretsId>58ce3a15-f56b-4b7a-910e-b13e8c288ec9</UserSecretsId>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <UseWinFormsOutOfProcDesigner>True</UseWinFormsOutOfProcDesigner>

    <!-- Target Windows SDK installed on your machine -->
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformIdentifier>Windows</TargetPlatformIdentifier>
    <TargetPlatformVersion>10.0.26100.0</TargetPlatformVersion>
    <SupportedOSPlatformVersion>10.0.26100.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Crossword_Filler</RootNamespace>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <NoWarn>$(NoWarn);NU1605</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="CluesReference\clue reference.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Dictionaries\index.aff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Dictionaries\index.dic">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="tessdata\eng.traineddata">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <COMReference Include="stdole">
      <Guid>{00020430-0000-0000-C000-000000000046}</Guid>
      <VersionMajor>2</VersionMajor>
      <VersionMinor>0</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>primary</WrapperTool>
      <Isolated>False</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\Next.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\copy.png" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="2025-08-29 18_33_09-DailyMailCrossword Filler - Microsoft Visual Studio.png" />
    <Content Include="2025-08-30 11_42_13-C__Users_cyber_Downloads_Crossword - File Explorer.ico" />
    <Content Include="favicon.ico" />
    <None Update="Hunspellx64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Hunspellx86.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Content Include="Properties\open.ico" />
    <Content Include="MenuIcons.ico" />
    <None Include="Resources\gangster-mafia-black-26429 %281%29.png" />
    <None Include="Resources\key-6298.png" />
    <None Include="Resources\information-348 %281%29.png" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="bin\Release\" />
    <Folder Include="Icons\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="ExCSS" Version="4.2.3" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.9" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
    <PackageReference Include="Microsoft.VisualBasic" Version="10.3.0" />
    <PackageReference Include="NetSpell" Version="2.1.7" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NHunspell" Version="1.2.5554.16953" />
    <PackageReference Include="OpenAI" Version="2.7.0" />
    <PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.11.0.20250507" />
    <PackageReference Include="Stub.System.Data.SQLite.Core.NetFramework" Version="1.0.115.5" />
    <PackageReference Include="Svg" Version="3.4.7" />
    <PackageReference Include="System.ClientModel" Version="1.8.1" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Data.SQLite" Version="1.0.113.0" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.115.5" />
    <PackageReference Include="System.Data.SQLite.EF6" Version="1.0.115.5" />
    <PackageReference Include="System.Data.SQLite.Linq" Version="1.0.115.5" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="8.0.1" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.22" />
    <PackageReference Include="System.IO.Pipelines" Version="10.0.0" />
    <PackageReference Include="System.Memory.Data" Version="8.0.1" />
    <PackageReference Include="System.Net.ServerSentEvents" Version="9.0.9" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
    <PackageReference Include="System.Text.Encodings.Web" Version="10.0.0" />
    <PackageReference Include="System.Text.Json" Version="10.0.0" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
    <PackageReference Include="Tesseract.Drawing" Version="5.2.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>